### ISSUE TITLE
Awareness

### ISSUE THREAD

**Issue by vigi86** [vigi86/HSLU_Zusammenfassungen#13]
Joey übernimmt Awareness Teil

**Comment by vigi86** [comment]
Braucht Feinschliff und Frage noch offen

**Comment by vigi86** [comment]
**Sie kennen die relevanten Erfolgsfaktoren der Mitarbeiter-Sensibilisierung und-Schulung und können diese in einer Kampagne umsetzen** muss noch beantwortet werden

**Comment by simonai1254** [comment]
MMn. Punkt der nicht direkt im Unterricht angesprochen wurde, überlappt sich stark mit der Durchführung der Awarenesskampagne. Kann entsprechend ignoriert werden

**Comment by vigi86** [comment]
> MMn. Punkt der nicht direkt im Unterricht angesprochen wurde, überlappt sich stark mit der Durchführung der Awarenesskampagne. Kann entsprechend ignoriert werden

Ja, gebe ich dir Recht. Ist trotztem als einzelne Abgrenzungsfrage definiert, sollte deshalb zu erwarten sein, dass etwas in dieser Richtung kommt. Wurde durch anderen Contributer ergänzt.
