### ISSUE TITLE
Wortschreibfehler

### ISSUE THREAD

**Issue by Light5000** [vigi86/HSLU_Zusammenfassungen#24]
![grafik](https://user-images.githubusercontent.com/59114086/71685240-01ff2a00-2d98-11ea-8822-171de14a198e.png)

**Comment by vigi86** [comment]
![image](https://user-images.githubusercontent.com/8401847/71690454-1269d180-2da5-11ea-85f4-637d10096759.png)

**Comment by vigi86** [comment]
![image](https://user-images.githubusercontent.com/8401847/71690501-33cabd80-2da5-11ea-9ba8-c1e2c4caebf5.png)
In Verbindung mit der IT: Sich bewusst sein, wie Wertvoll Informationen sind und welches Ausmass es haben kann, wenn diese an Unbefugte gelangen. Wie z.B. Passwörter für den Fernzugriff auf die wichtigsten Servern.

**Comment by vigi86** [comment]
erledigt
